# Site settings
title: Heirloom Liqueurs
email: info@heirloomliqueurs.com
description: ''
url: "http://heirloomliqueurs.com"
permalink: pretty
analytics_code: UA-106357720-2 # accessible via dev@ocupop.com

instagram_url: https://instagram.com/heirloomliqueurs


# Collections
# collections:
#   examples:
#     output: true
#     layout: default
#     permalink: /examples/:path/

# defaults:
#   - 
#     scope:
#       type: 'examples'
#     values:
#       layout: default
#       variable_name: value

# Build settings
safe: false
source: src


plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
