# Site settings
title: Heirloom Liqueurs
email: info@heirloomliqueurs.com
description: ''
url: "http://heirloomliqueurs.com"
permalink: pretty
analytics_code: UA-106357720-2 # accessible via dev@ocupop.com

instagram_url: https://instagram.com/heirloomliqueurs
facebook_url:

placeholders:
  banner_image: https://via.placeholder.com/1800x800?text=Placeholder+Banner
  thumbnail_image: https://via.placeholder.com/768x576?text=Placeholder+Thumbnail


# Collections
collections:
  products:
    output: true
    layout: product
    permalink: /products/:path/

# defaults:
#   - 
#     scope:
#       type: 'examples'
#     values:
#       layout: default
#       variable_name: value

# Build settings
safe: false
source: src


plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-contentblocks

_options:
  layout:
    hidden: true

_comments:
  product_description: 'Description for the Collection page'
  product_image: 'Displays on the Product page'
  banner_image: 'Displays on the Product page'
  grid_image: 'Displays on the Collection page'
