title: Heirloom Liqueurs
email: info@heirloomliqueurs.com
description: 'Heirloom Brand was started with one goal in mind: to create vibrant liqueurs with whole botanicals.'
url: "http://heirloomliqueurs.com"
permalink: pretty
analytics_code: UA-106357720-2 # accessible via dev@ocupop.com
share_image: /img/heirloom-share-image.png
twitter:
  username: HeirloomLiquors
  card: summary

instagram_url: https://instagram.com/heirloomliqueurs
facebook_url: https://www.facebook.com/heirloomliqueurs/

placeholders:
  banner_image: https://via.placeholder.com/1800x800?text=Placeholder+Banner
  thumbnail_image: https://via.placeholder.com/768x576?text=Placeholder+Thumbnail
  product_image: '/img/pineapple-bottle.png'


# Collections
collections:
  products:
    output: true
    layout: product
    permalink: /products/:path/
  cocktails:
    output: true
    layout: cocktails
    permalink: /cocktails/:path/  

# Build settings
safe: false
sass:
  # style: compressed
  sass_dir: _scss

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-contentblocks

_options:
  layout:
    hidden: true

_comments:
  product_description: 'Description for the Collection page'
  product_image: 'Displays on the Product page'
  banner_image: 'Displays on the Product page'
  grid_image: 'Displays on the Collection page'

cloudcannon:
  collections:
    cocktails:
      _singular_name: Cocktail